<Project Sdk="Microsoft.NET.Sdk">

	<!-- Project -->
	<PropertyGroup Label="project">
		<TargetFrameworks>net10.0</TargetFrameworks>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>

		<AssemblyName>OwlShed.Hushit.Data</AssemblyName>
		<RootNamespace>OwlShed.Hushit.Data</RootNamespace>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Deterministic>true</Deterministic>

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
		<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
	</PropertyGroup>

</Project>
