<Project Sdk="Microsoft.NET.Sdk">

	<!-- Project -->
	<PropertyGroup Label="project">
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>

		<AssemblyName>hushit</AssemblyName>
		<RootNamespace>OwlShed.Hushit.Monolith</RootNamespace>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>CS1591</NoWarn>
		<Deterministic>true</Deterministic>

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<PublishAot>false</PublishAot>
		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">false</IsAotCompatible>
		<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">false</IsTrimmable>
	</PropertyGroup>

	<!-- Project references -->
	<ItemGroup Label="projects">
		<ProjectReference Include="../../interaction/Interaction/Interaction.csproj" />
	</ItemGroup>

	<!-- Package references -->
	<ItemGroup Label="packages">
		<PackageReference Include="GirCore.Gtk-4.0" Version="0.8.1" />
		<PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

</Project>
